apiVersion: v1
kind: Service
metadata:
  name: pathnex-backend-service

spec:
  selector:
    app: pathnex-backend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP
