name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Show files
        run: ls -la

      - name: Run script
        run: |
          set -e
          ./scripts/script.sh

      - name: Run health check
        run: |
          set -e
          ./scripts/healthScript.sh